# Generated by Django 6.0.3 on 2026-04-01 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_project_module_task_bug_timelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_staff', 'Can staff')]},
        ),
        migrations.AlterField(
            model_name='bug',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to='core.user'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='reported_by',
            field=models.ForeignKey(db_column='reported_by', on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to='core.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to='core.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='core.user'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='developer',
            field=models.ForeignKey(db_column='developer_id', on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='core.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='core_user_set', related_query_name='core_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_set', related_query_name='core_user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
